### ISSUE TITLE
Undo is kinda broken.

### ISSUE THREAD

**Issue by hanss314** [Saritus/Game-of-Life-and-Death#1]
Undo move changes the cell color to the color of the player who is making the move.

**Comment by Saritus** [comment]
Thank you very much.
It should be fixed with https://github.com/Saritus/Game-of-Life-and-Death/commit/7d6660e2c387be111eb1a9e7cf32f5116c4ef3e4

**Comment by hanss314** [comment]
You can close the issue yourself when you've fixed it
